use DWVLT_ALV_CFB
go
DROP TABLE IF EXISTS AVALIACAO;
DROP TABLE IF EXISTS RECEITA;
DROP TABLE IF EXISTS PRODUTORA;
DROP TABLE IF EXISTS CALENDARIO;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS CHURN;
DROP TABLE IF EXISTS FILME;
DROP TABLE IF EXISTS USUARIO;